Remove function 'inline' declarations
The inline declaraction caused the macOS High Sierra linker to fail to find the
symbols for the inline functions. The error was:
"ld: symbol(s) not found for architecture x86_64"